import time
a=time.time()
print("Seconds since epoch :",a,end='\n----------\n')
print("Current date and time:")
print(time.ctime(a),end='\n----------\n') 
time.sleep(1)
print("Local time :")
print(time.localtime(a),end='\n----------\n')
print("Local time in UTC format :")
print(time.gmtime(a),end='\n-----------\n')
b=(2019,8,6,10,40,34,1,218,0)
print("Current Time in seconds :")
print( time.mktime(b),end='\n----------\n')
print("Current Time in local format :")
print( time.asctime(b),end='\n----------\n')
c = time.localtime()
d = time.strftime("%m/%d/%Y, %H:%M:%S", c)
print("String representing date and time:")
print(d,end='\n----------\n')
print("time.strptime parses string and returns it in struct_time format :\n")
e = "06 AUGUST, 2019"
f = time.strptime(e, "%d %B, %Y")
print(f)